name: Linter

on:
  push:
    branches:
      - "master"
  pull_request:

env:
  default_node_version: 14

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ env.default_node_version }} and Cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.default_node_version }}
          cache: npm
          cache-dependency-path: "package.json"
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
