name: Tester

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  tester:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: ['14.x', '16.x', '18.x']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }} and Cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: "package.json"
      - name: Install Dependencies
        run: npm install
      - name: Test
        run: npm run test

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js 14 and Cache
        uses: actions/setup-node@v4
        with:
          node-version: 14
          cache: npm
          cache-dependency-path: "package.json"
      - name: Install Dependencies
        run: npm install
      - name: Coverage
        run: npm run test-cov
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.github_token }}